### ISSUE TITLE
Data for Pre-training

### ISSUE THREAD

**Issue by amitbcp** [rasmusbergpalm/attend-copy-parse#1]
Hi @rasmusbergpalm ,

Thanks for open sourcing the code for the paper. Can you share the invoice dataset mentioned in the paper to carry out similar experiments and reproduce the results ?

**Comment by rasmusbergpalm** [comment]
No, unfortunately I cannot. I don't own it. Tradeshift does. You can consider contacting them, but they will not be able to share it either, since that'd massively violate the privacy of their customers.
