### ISSUE TITLE
Invoice image corresponding to sample.json file

### ISSUE THREAD

**Issue by sniper0110** [rasmusbergpalm/attend-copy-parse#3]
Hey there,

Thanks for open sourcing this!
I have a question regarding the data. Is it possible for your to provide the image of the invoice corresponding to the [sample.json](https://github.com/rasmusbergpalm/attend-copy-parse/blob/master/tasks/acp/data/sample.json) file please?

It would be very helpful to understand how the information on the image corresponds to the information inside the .json file.

Thanks in advance!

**Comment by rasmusbergpalm** [comment]
I do actually! and it's one of my own so I can share it. Here you go

[faktura-1.pdf](https://github.com/rasmusbergpalm/attend-copy-parse/files/8243391/faktura-1.pdf)
